ALBSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: ALB - allow HTTPS from anywhere
    VpcId:
      Ref: MitmVpc
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
        Description: HTTPS
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-alb-sg'
