MitmALB:
  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  Properties:
    Name:
      Fn::Sub: '${AWS::StackName}-alb'
    Scheme: internet-facing
    Type: application
    SecurityGroups:
      - Ref: ALBSecurityGroup
    Subnets:
      - Ref: MitmSubnetA
      - Ref: MitmSubnetB
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-alb'
