MitmProxyTargetGroup:
  Type: AWS::ElasticLoadBalancingV2::TargetGroup
  Properties:
    Name:
      Fn::Sub: '${AWS::StackName}-proxy-tg'
    Port: 8080
    Protocol: HTTP
    VpcId:
      Ref: MitmVpc
    TargetType: instance
    Targets:
      - Id:
          Ref: MitmInstance
    HealthCheckPath: /health
    HealthCheckPort: '8081'
    HealthCheckProtocol: HTTP
    HealthyThresholdCount: 2
    UnhealthyThresholdCount: 3
    HealthCheckIntervalSeconds: 30
