MitmPublicRoute:
  Type: AWS::EC2::Route
  DependsOn: MitmVpcGatewayAttachment
  Properties:
    RouteTableId:
      Ref: MitmRouteTable
    DestinationCidrBlock: 0.0.0.0/0
    GatewayId:
      Ref: MitmInternetGateway
